### ISSUE TITLE
プルリクエストの更新内容が自動で本番に反映されてしまう

### ISSUE THREAD

**Issue by willnet** [ginzarb/ginzarb.github.io#29]
.travis.yml のフックが全プルリクエストで動いているのが原因

**Comment by willnet** [comment]
[ginzarb.github.io/.travis.yml at source · ginzarb/ginzarb.github.io](https://github.com/ginzarb/ginzarb.github.io/blob/source/.travis.yml#L22) source ブランチにコミットさえ積まれなければ大丈夫っぽい

**Comment by y-yagi** [comment]
あれ。だとすると、何で #28 は反映されちゃったんだろう。

**Comment by willnet** [comment]
本当だ。なぜなのか

**Comment by willnet** [comment]
GitHub Actions化によりこの問題も解決したはず
