### ISSUE TITLE
DoorKeeper の API 仕様変更対応

### ISSUE THREAD

**Issue by willnet** [ginzarb/ginzarb.github.io#30]
> 最終的には認証なしAPIの提供を停止させて頂く予定です。
> 正確な日付は決まっていませんが、2016年5月31日以降を計画しています。
> 認証付きAPIへの移行が困難な場合は、こちらにてお問い合わせください。

[APIアクセスに認証が必要になります | Doorkeeper](https://www.doorkeeper.jp/news/2016/3/1/update-to-api)

**Comment by y-yagi** [comment]
![df37f3436d75c7c81e5311e03a5fc64d.jpg (500×267)](http://img.lovelive-matome.com/2014/09/df37f3436d75c7c81e5311e03a5fc64d.jpg)

**Comment by y-yagi** [comment]
んー、どうしようかなあ。お申し込みフォームの設置の方使っても良いけど、毎回設定するのは手間かなあ…。

**Comment by willnet** [comment]
![ミサワ](https://d20qqtosks8wga.cloudfront.net/5/0/50e25871.gif)

**Comment by y-yagi** [comment]
[![惚れさせ514 「大玉転がし」 川から水をひいてくれば 大玉なんかも ああして簡単に 運ぶことが 可能なんだよ](http://livedoor.blogimg.jp/jigokuno_misawa/imgs/f/f/ff12fb47.gif)](http://jigokuno.com/eid_540.html)
